# IMPORTANT / IMPORTANT / IMPORTANT / IMPORTANT / IMPORTANT / IMPORTANT / IMPORTANT / IMPORTANT /
# If you are going to use the sound feature, make sure you are using 1.13.2 sound names.
# It doesn't matter if you are on lower versions. it'll work regardless. as long as its in the game, of course. If you need help, feel free to join our discord. (listed in the resource section)
# Here's the link: https://helpch.at/docs/1.13.2/org/bukkit/Sound.html
#
# EXAMPLE
#  (WORLD-NAME):
#    lock: false // If its enabled, it would not let the player go to the dimension through the portal.
#    permission: "ld.nether" // This cannot be empty. If the player does not have this permission. it would not let them through.
#    succeed-message: "Welcome welcome!" // If this is empty. it wouldn't send anything. when player has permission.
#    broadcast-message: "%player_name% has traveled to the nether." // If this is empty. it wouldn't send anything. If the player succeeds to go to the dimension, it would broadcast a message to everyone.
#    denied-message: "You do not have permission to go to the nether." // when player does not have message.
#    locked-message: "Nether is locked." If this is empty. it wouldn't send anything. when its locked.
#    succeed-sound: CLICK // this is optional. played when the player is going to the world
#    denied-sound: CLICK // this is optional. played when the player does not have permission.
#    locked-sound: CLICK this is optional. played when the world is locked

settings:
  # if you would like not to get notified once there's an update, tick it to false
  notify-updates: true
  # If you would like to get notified if the world/sound doesn't exist (in the console). tick it to true
  check-errors: false

dimensions:
  example_world:
    lock: false
    permission: "ld.example_world"
    succeed-message: "Welcome welcome!"
    broadcast-message: "%player_name% has traveled to the nether."
    denied-message: "You do not have permission to go to the example_world."
    locked-message: "example_world is locked."
    succeed-sound: CLICK
    denied-sound: CLICK
    locked-sound: CLICK
    succeed-commands:
      - "[CONSOLE] Kick Tofpu"
      -
  example_end:
    lock: true
    permission: "ld.example_end"
    succeed-message: ""
    broadcast-message: "%player_name% has traveled to the nether."
    denied-message: "You do not have permission to go to the example_end."
    locked-message: ""
    succeed-sound: CLICK
    denied-sound: CLICK
    locked-sound: CLICK
  example_the_end:
    lock: false
    permission: "ld.example_the_end"
    succeed-message: ""
    broadcast-message: "%player_name% has traveled to the nether."
    denied-message: "You do not have permission to go to the example_the_end."
    locked-message: "example_the_end is locked."
    succeed-sound: CLICK
    denied-sound: CLICK
    locked-sound: CLICK