settings:
  # if you would like not to get notified once there's an update, tick it to false
  notify-updates: true
  # If you would like to get notified if the world/sound doesn't exist (in the console). tick it to true
  check-errors: false

dimensions:
  example_world:
    lock: false
    permission: "ld.example_world"
    succeed-message: "Welcome welcome!"
    broadcast-message: "%player_name% has traveled to the nether."
    denied-message: "You do not have permission to go to the example_world."
    locked-message: "example_world is locked."
    succeed-sound: CLICK
    denied-sound: CLICK
    locked-sound: CLICK
  example_nether:
    lock: true
    permission: "ld.example_nether"
    succeed-message: ""
    broadcast-message: "%player_name% has traveled to the nether."
    denied-message: "You do not have permission to go to the example_nether."
    locked-message: ""
    succeed-sound: CLICK
    denied-sound: CLICK
    locked-sound: CLICK
  example_the_end:
    lock: false
    permission: "ld.example_the_end"
    succeed-message: ""
    broadcast-message: "%player_name% has traveled to the nether."
    denied-message: "You do not have permission to go to the example_the_end."
    locked-message: "example_the_end is locked."
    succeed-sound: CLICK
    denied-sound: CLICK
    locked-sound: CLICK