# The documentation page can be seen at https://docs.tofpu.me/plugins/lockeddimension.

settings:
  # Get notified when there's an update.
  notify-updates: true
  # Get notified when you configured something wrong.
  check-errors: false

dimensions:
  world_name:
    # Restrict the dimension entrance?
    lock: false

    # Require the player to have this permission node;
    # can be left empty.
    permission: "required_permission"

    # This message is sent to the player when they go through
    # the dimension successfully; can be left empty.
    succeed-message: "Welcome to World!"

    # This message is broadcasted globally when they go through
    # the dimension successfully; can be left empty.
    broadcast-message: "%player_name% has traveled to the world!"

    # This message is sent to the player when they lack the
    # the permission node above; this won't be triggered if
    # the permission node was left empty.
    denied-message: "You lack the permission to go through this dimension!"

    # This message is sent to the player when the
    # dimension is locked; this won't be sent if
    # the lock option was set to false.
    locked-message: "The dimension is locked. Come back later!"

    # This sound is sent to the player when they go through
    # the dimension successfully; can be left empty.
    succeed-sound: CLICK

    # This sound is sent to the player when they lack the
    # the permission node above; this won't be triggered if
    # the permission node was left empty.
    denied-sound: CLICK

    # This sound is sent to the player when the
    # dimension is locked; this won't be triggered
    # if the lock option was set to false.
    locked-sound: CLICK