name: LockedDimension
version: ${project.version}
main: me.tofpu.lockeddimension.LockedDimension
api-version: 1.13
authors: [Tofpu]
softdepend:
  - PlaceholderAPI
description: A plugin which its purpose is lock certain dimensions behind a permission node.
commands:
  lockeddimension:
    description: lockeddimension command
    permission: lockeddimension.use
