name: LockedDimension
description: You could disable, lock dimensions behind permissions nodes, and much more!
version: ${project.version}
main: me.tofpu.lockeddimension.LockedDimension
api-version: 1.13
authors: [Tofpu]
softdepend:
  - PlaceholderAPI
commands:
  lockeddimension:
    description: A command
